version: '3'
services:
# ---------------------- images ----------------------
# only redis exposed to host (for testing and a time)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 29092:29092
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
  redis:
    image: redis
    container_name: redis
    ports:
      - 26379:6379
# ---------------------- builds ----------------------
# only API and file exposed to host
  api:
    build: ./rest-gateway
    container_name: api
    ports:
      - 31374:1374
    depends_on:
      - kafka
      - redis
    volumes:
      - ./volumes/shared:/usr/app/shared
    environment:
      - NAME=rest_api_gate
      - PORT=1374
      - TOKEN_SECRET=secret
      - TOEKN_TTL=4h
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CONSUMER=rest_api_gate
  file:
    build: ./files-repository
    container_name: file
    depends_on:
      - kafka
      - redis
    ports:
      - 31375:1375
    volumes:
      - ./volumes/file:/usr/app/file
    environment:
      - NAME=files
      - PORT=1375
      - REDIS=redis:6379
      - KAFKA_BROKERS=kafka:9092
      - TOKEN_SECRET=secret
      - TOKEN_TTL=4h
      - MONGO=mongodb://mongo:27017/files
      - PHOTO_MAXSIZE=2 MB
      - VIDEO_MAXSIZE=100 MB
      - AUDIO_MAXSIZE=20 MB
      - DOC_MAXSIZE=200 MB
      - PHOTO_PATH=file/photo
      - AUDIO_PATH=file/audio
      - VIDEO_PATH=file/video
      - DOC_PATH=file/doc
  admin:
    build: ./microservices/admin
    container_name: admin
    depends_on:
      - kafka
      - redis
      - mongo
    environment:
      - NAME=admin-service
      - MONGO=mongodb://mongo:27017/admin
      - REDIS=redis:6379
      - KAFKA_BROKERS=kafka:9092
  note:
    build: ./microservices/note
    container_name: note
    depends_on:
      - kafka
      - redis
      - mongo
    environment:
      - NAME=note-service
      - REDIS=redis:6379
      - REDIS_EXPIRETIME=5
      - MONGO=mongodb://mongo:27017/note_cms
      - KAFKA_BROKER=kafka:9092
      - KAFKA_GROUPID=note-consumer
