version: '3'
services:
# ---------------------- images ----------------------
# only redis exposed to host (for testing and a time)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 29092:29092
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
  redis:
    image: redis
    container_name: redis
    ports:
      - 26379:6379
# ---------------------- builds ----------------------
# only API and file exposed to host
  api:
    build: ./rest-gateway
    container_name: api
    ports:
      - 31374:1374
    depends_on:
      - kafka
      - redis
  file:
    build: ./files-repository
    container_name: file
    depends_on:
      - kafka
      - redis
    ports:
      - 31375:1375
    volumes:
      - ./volumes/file:/usr/app/file
  admin:
    build: ./microservices/admin
    container_name: admin
    depends_on:
      - kafka
      - redis
      - mongo
  note:
    build: ./microservices/note
    container_name: note
    depends_on:
      - kafka
      - redis
      - mongo